# Generated by Django 4.2.7 on 2023-11-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_msg_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgentry',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='simple_msg_server.msgform'),
        ),
    ]
