# Generated by Django 4.2.7 on 2023-11-15 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_msg_server', '0002_alter_msgentry_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgentry',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
