# Generated by Django 4.2.7 on 2023-11-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_msg_server', '0003_alter_msgentry_read_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='msgentry',
            options={'ordering': ['-created']},
        ),
    ]
