# Generated by Django 4.2.7 on 2023-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_msg_server', '0004_alter_msgentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgform',
            name='endpoint',
            field=models.UUIDField(auto_created=True),
        ),
    ]
